### ISSUE TITLE
Import/Export field wrong url

### ISSUE THREAD

**Issue by krivinarius** [reduxframework/redux-framework#2197]
After updating to ReduxFramework 3.5 import-export field can't load its js and css scripts in the admin.
I tracked it down to $this->extension_url being incorrect.

This is how the url to js script looks like on my local installation:
http://testsite.local/wp/var/www/html/my-site/content/plugins/redux-framework/ReduxCore/inc/extensions/import_export/import_export/field_import_export.min.js?ver=4.0

All other field scripts load correctly.

Note: I'm using this configuration https://github.com/markjaquith/WordPress-Skeleton

**Comment by kprovance** [comment]
So, which part of that URL is incorrect?

**Comment by krivinarius** [comment]
Look at the url structure, it is appending var/www/html/my-site

The url should look like this http://testsite.local/content/plugins/redux-framework/ReduxCore/assets/js/media/media.min.js?ver=1428352456 (this one works fine)

**Comment by kprovance** [comment]
http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by krivinarius** [comment]
Upon clicking on "Generate a Support URL" I'm getting JavaScript alert saying that there was an error.

**Comment by dovy** [comment]
Please look at your Javascript console and tell us the error.

Or if it's a live site, please provide login information to us via support@reduxframework.com

**Comment by kprovance** [comment]
Belay that, the information is in the network tab (Chrome).  If you clear that data, click the Generate a Support URL Button again, select the first instance of admin-ajax, and click the Response tab, the info we need is there.

**Comment by krivinarius** [comment]
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: mysqli_connect(): (28000/1045): Access denied for user 'www-data'@'localhost' (using password: NO) in /var/www/html/wp-class/content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php on line <i>179</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>240648</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/wp-class/wp/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>../admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.4172</td><td bgcolor='#eeeeec' align='right'>16325864</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/var/www/html/wp-class/wp/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>../admin-ajax.php<b>:</b>86</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.4172</td><td bgcolor='#eeeeec' align='right'>16327440</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array' target='_new'>call_user_func_array</a>
(  )</td><td title='/var/www/html/wp-class/wp/wp-includes/plugin.php' bgcolor='#eeeeec'>../plugin.php<b>:</b>496</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.4172</td><td bgcolor='#eeeeec' align='right'>16327704</td><td bgcolor='#eeeeec'>Redux_Welcome->support_hash(  )</td><td title='/var/www/html/wp-class/wp/wp-includes/plugin.php' bgcolor='#eeeeec'>../plugin.php<b>:</b>496</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.4266</td><td bgcolor='#eeeeec' align='right'>16786824</td><td bgcolor='#eeeeec'>Redux_Helpers::getTrackingObject(  )</td><td title='/var/www/html/wp-class/content/plugins/redux-framework/ReduxCore/inc/welcome/welcome.php' bgcolor='#eeeeec'>../welcome.php<b>:</b>116</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.4497</td><td bgcolor='#eeeeec' align='right'>16906192</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.mysqli-connect' target='_new'>mysqli_connect</a>
(  )</td><td title='/var/www/html/wp-class/content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php' bgcolor='#eeeeec'>../class.redux_helpers.php<b>:</b>179</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: mysqli_error() expects parameter 1 to be mysqli, boolean given in /var/www/html/wp-class/content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php on line <i>179</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>240648</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/wp-class/wp/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>../admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.4172</td><td bgcolor='#eeeeec' align='right'>16325864</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='/var/www/html/wp-class/wp/wp-admin/admin-ajax.php' bgcolor='#eeeeec'>../admin-ajax.php<b>:</b>86</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.4172</td><td bgcolor='#eeeeec' align='right'>16327440</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array' target='_new'>call_user_func_array</a>
(  )</td><td title='/var/www/html/wp-class/wp/wp-includes/plugin.php' bgcolor='#eeeeec'>../plugin.php<b>:</b>496</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.4172</td><td bgcolor='#eeeeec' align='right'>16327704</td><td bgcolor='#eeeeec'>Redux_Welcome->support_hash(  )</td><td title='/var/www/html/wp-class/wp/wp-includes/plugin.php' bgcolor='#eeeeec'>../plugin.php<b>:</b>496</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.4266</td><td bgcolor='#eeeeec' align='right'>16786824</td><td bgcolor='#eeeeec'>Redux_Helpers::getTrackingObject(  )</td><td title='/var/www/html/wp-class/content/plugins/redux-framework/ReduxCore/inc/welcome/welcome.php' bgcolor='#eeeeec'>../welcome.php<b>:</b>116</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.4501</td><td bgcolor='#eeeeec' align='right'>16906328</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.mysqli-error' target='_new'>mysqli_error</a>
(  )</td><td title='/var/www/html/wp-class/content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php' bgcolor='#eeeeec'>../class.redux_helpers.php<b>:</b>179</td></tr>
</table></font>
Error 



My test site is local. I'm working on a new theme. I have another one that is using Redux but that one is using 3.4.x

Here is where my original problem happens:
ReduxCore/inc/extensions/import_export/import_export/field_import_export.php 

lines 50 and 51
$this->extension_dir = trailingslashit( str_replace( '\\', '/', dirname( __FILE__ ) ) );
$this->extension_url = site_url( str_replace( trailingslashit( str_replace( '\\', '/', ABSPATH ) ), '', $this->extension_dir ) );

**Comment by kprovance** [comment]
Yes, I am aware of your original issue.  I cannot duplicate it, so I need the support URL data, but since that doesn't appear to be working, that needs to be fixed first.  Please upgrade to v3.5.0.3 from this repo, and then try the support URL instructions again, please.

**Comment by krivinarius** [comment]
http://support.redux.io/?id=8M%2FvPYztcBHysLxBuhIUdYdqYIuvXDTmM2KvLPb616k9t742BMgIEKPW2tOUcG7fIW%2Fak9hFidmRTb7Guk0sqA%3D%3D

**Comment by kprovance** [comment]
v3.5.0.4 should resolve this.  You have WP installed in some funky way that causes our logic to break.  Anyways, it should be resolved.

**Comment by krivinarius** [comment]
Thanks.

**Comment by dovy** [comment]
If you like Redux, or the support we render, please do one or all of the following:

* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework

**Comment by krivinarius** [comment]
It's still not working.

It works like this:

$this->extension_dir = ReduxFramework::$_dir . 'inc/extensions/import_export/import_export/'; 
$this->extension_url = ReduxFramework::$_url . 'inc/extensions/import_export/import_export/';

**Comment by dovy** [comment]
Whoops! Push has been fixed. This is why we have a development branch.  :P

**Comment by kprovance** [comment]
@krivinarius - What you proposed broke this feature for everyone with proper WP installs.  We had to go back to the prior way.

**Comment by dovy** [comment]
Chances are your siteurl that you define for WP doesn't have a trailing slash like it is thus required. It is suggested that you fix your URL accordingly.

**Comment by ottok** [comment]
@krivinarius Try the fix suggested in this PR: https://github.com/reduxframework/redux-framework/pull/2754 - please report back your experience testing it.
