### ISSUE TITLE
There was a problem with your action. Please try again or reload the page.

### ISSUE THREAD

**Issue by gohri** [reduxframework/redux-framework#3124]
I'm getting this error when clicking "Save Changes" button in redux framework option panel

**Comment by a-gitlin** [comment]
I'm receiving the error when trying to make updates and I'm not sure how to resolve.  I'm on the latest version of WP and Redux. Here's a screenshot of the console log.  Any help would be much appreciated.  
<img width="1238" alt="screen shot 2016-09-19 at 11 57 10 pm" src="https://cloud.githubusercontent.com/assets/22312335/18657765/43646462-7ecb-11e6-8a1a-362355c6b047.png">

**Comment by kprovance** [comment]
Internal server errors are just that, server errors.  Something is going on with your server settings, I suspect. Since the problem resolves around the WP ajax, that's where the conflict lays.  Once that's resolved, the ajax save should work fine.

**Comment by a-gitlin** [comment]
@kprovance Thanks for the response.  After some digging and trail and error, I discovered that the Wordpress Jetpack plugin was somehow conflicting with the ability to save theme options with Redux.  I deactivated that plugin and everything is working just fine now within my them options panel. Now to figure out which of the million installed plugins my client actually uses.

**Comment by dovy** [comment]
Always an adventure.  ;)

**Comment by sourabgupta88** [comment]
hi!

It can be the problem due to version of php.

Try this solution to see if it works.

/wp-content/plugins/redux-framework/ReduxCore/framework.php

go to line 4069

there you find such option 
$args = array_merge( array( $current_user ), func_get_args() );

change it to 
$name_arr=func_get_args();
               $args = array_merge( array( $current_user ),$name_arr  );

test if it works. Cheers.

**Comment by castilloedwin** [comment]
Muchas gracias, estaba teniendo exactamente este mismo problema. Gracias @sourabgupta88

**Comment by mlenders** [comment]
@sourabgupta88 thank u very very very much! u saved me!

**Comment by sourabgupta88** [comment]
@mlenders , @castilloedwin Its my pleasure to help you guys.

**Comment by kprovance** [comment]
What version of PHP is this is an issue in?  I never got a support URL/hash for this issue, so I have no idea.  If it's a PHP 7.x issue, it would be helpful to know, so I can make this change permanent.

**Comment by sourabgupta88** [comment]
hi!
@kprovance it is happening because array_merge in earlier version of php expect two variables should be of array type and cannot accept one input as array and other as function. However, we know that output of function will be array but it is not applicable till php v 7.x . I hope I gave you the answer you are looking.

**Comment by kprovance** [comment]
Somewhat.  What version of PHP specifically did it fail on, was my curiosity.

**Comment by sourabgupta88** [comment]
hi!

I had tested it on  php version <=5.3.13 . On all those versions it failed without the fix.

**Comment by kprovance** [comment]
Huh.  Interesting.  That code used to run on 5.2 without any problems.  Well, if this fix is universal, then it shouldn't hurt anything.  Do you know if it works with 7.0 and 7.1?  I've seen a LOT of issues with arrays and isset with 7.1.

**Comment by sourabgupta88** [comment]
Sorry! I did not test on 7.1 version till now. But I think it should not because they had not changed anything in its definition till php version 7.1

**Comment by kprovance** [comment]
Very good.  This fix will be in the next release.  BTW, I realize now why we didn;t catch this till now.  The section of code it occurs in was a recent user submission that apparently was not tested on older versions of PHP.  Anyways, gave you credit for the assist.  Cheers!

**Comment by sourabgupta88** [comment]
Thanks a lot @kprovance .

**Comment by Kwilliams94** [comment]
@sourabgupta88 THANK YOU! This was a problem that not even my hosting service could handle and I have little knowledge of php so much appreciated!

**Comment by sourabgupta88** [comment]
I am glad that my research helped you(@Kwilliams94) . Owner of the plugin is already aware of the issue. In the next version people will not face this issue as he will get it fixed. Cheers :-)

**Comment by kprovance** [comment]
The fix exists in the version of Redux in this repo.  You are free to download and embed or install as a plugin via TGM.  We will eventually update wp.org with this version.  It was user contributed code that caused this issue, and I apologize for not vetting is closer under environments below PHP 5.3

**Comment by ledugani** [comment]
@sourabgupta88 new to programming. how do you access /wp-content/plugins/redux-framework/ReduxCore/framework.php ?

**Comment by kprovance** [comment]
You really don't want to go editing the Redux core.  Anything you change will be lost when we update.  This particular issue has been fixed in the version of Redux available in this git.

**Comment by ledugani** [comment]
@kprovance I have 3.6.5, is this the latest version? I am still getting the error message "There was a problem with your action. Please try again or reload the page." under theme options.

**Comment by kprovance** [comment]
I just said the issue was fixed in the version available in this git repo, which is newer.

**Comment by ledugani** [comment]
Any idea why I am still having the same issue @kprovance ?

**Comment by kprovance** [comment]
None.  You piggy backed an old ticket and provided none of the information we require for support.  Sorry.

**Comment by ledugani** [comment]
Great. Thanks for all the help.

**Comment by saledesma** [comment]
Dear, I appreciate the immediate help. But, I downloaded the latest version and I still have the problem. What I can do? I have the client waiting for my job.

**Comment by kprovance** [comment]
Please do not piggy back old issues.  If you are not the author of the theme, then you need to contact the author for support.  We are not the theme's author.  If you are the theme author, then please open a new ticket, making note of all the test in that window, that is, instructions on what data we require.

Locking this thread due to piggybacking issues.
